path:
  train_data_path: data/train_odps.txt
  valid_data_path: data/test_odps.txt
  vocab_path: vocab/train_kbs_zhidao_word.txt
  word_embed_path: vocab/zhidao_skipgram_200.bin
  save_model_path: checkpoints/model.ckpt

hparams: &DEFAULT
  num_spl_steps: 3000
  num_warmup_steps: 300
  max_len: 30
  batch_size_train: 64
  batch_size_eval: 1024
  num_epoch: 300
  earlystop_patience: 1000
  # 可调
  filter_sizes: [3, 4, 5]
  num_filters: 100
  learning_rate: 5.0e-4
  decay_rate: 1.0
  decay_steps: 1000
  grad_max: 6
  dropout_rate: 0.7
#  l2_constrain: 0
#  scale_l2: 0
  label_smoothing: 0

